import { CategoryPrompts, Ratio } from './types';

export const PROMPTS: CategoryPrompts = {
    "Fashion & Apparel": [
        { id: 1, en: "Generate a high-quality studio photo of {product_name} on a clean white background with soft shadows. Include the brand logo '{brand_name}' at top-right and add a minimal price tag saying '{price}'. Make it Instagram-ad style.", bn: "{product_name} এর একটি উচ্চ-মানের স্টুডিও ছবি তৈরি করুন; পরিষ্কার সাদা ব্যাকগ্রাউন্ড এবং মৃদু ছায়া সহ। উপরে ডানদিকে ব্র্যান্ড লোগো '{brand_name}' এবং নিচে মূল্য ট্যাগ '{price}' রাখুন। Instagram অ্যাড স্টাইল।" },
        { id: 2, en: "Create a lifestyle photo featuring {product_name} worn by a model in a minimal urban setting like a stylish cafe. Add a subtle logo watermark and a call-to-action: 'Shop Now'.", bn: "একজন মডেল দ্বারা পরিধানকৃত {product_name} একটি লাইফস্টাইল ফটো তৈরি করুন, একটি স্টাইলিশ ক্যাফের মতো মিনিমাল আরবান সেটিং সহ। লোগো ওয়াটারমার্ক রাখুন এবং 'Shop Now' CTA যোগ করুন।" },
        { id: 3, en: "Flat lay photography of {product_name}, surrounded by related accessories (e.g., watch, sunglasses). Neutral-toned, textured background. Text overlay: '{discount} OFF'.", bn: "{product_name} এর ফ্ল্যাট লে ফটোগ্রাফি, সম্পর্কিত জিনিসপত্র (যেমন, ঘড়ি, সানগ্লাস) দিয়ে সাজানো। নিউট্রাল টোনের টেক্সচার্ড ব্যাকগ্রাউন্ড। টেক্সট ওভারলে: '{discount} ছাড়'" },
        { id: 4, en: "Create an eye-catching ad featuring an AI-generated fashion model showcasing the {product_name}. The ad should have a clean, modern aesthetic. Include the provided brand logo subtly. Add an informative and catchy slogan about the product's quality. Overlay text: '{discount} OFF'.", bn: "একটি আকর্ষণীয় বিজ্ঞাপন তৈরি করুন যেখানে একজন AI-জেনারেটেড ফ্যাশন মডেল {product_name} প্রদর্শন করছেন। বিজ্ঞাপনের একটি পরিষ্কার, আধুনিক নান্দনিকতা থাকা উচিত। প্রদত্ত ব্র্যান্ড লোগোটি সূক্ষ্মভাবে অন্তর্ভুক্ত করুন। পণ্যের গুণমান সম্পর্কে একটি তথ্যপূর্ণ এবং আকর্ষণীয় স্লোগান যোগ করুন। ওভারলে টেক্সট: '{discount} ছাড়'." },
        { id: 5, en: "Design an infographic-style ad for the {product_name}. Highlight key features like '100% Cotton', 'Water-resistant', or 'Hand-stitched' using clean icons and text. The product should be centrally featured. Incorporate the brand logo and a special offer: '{discount} OFF'.", bn: "{product_name}-এর জন্য একটি ইনফোগ্রাফিক-স্টাইলের বিজ্ঞাপন ডিজাইন করুন। '100% কটন', 'ওয়াটার-রেসিস্ট্যান্ট', বা 'হ্যান্ড-স্টিচড'-এর মতো মূল বৈশিষ্ট্যগুলি পরিষ্কার আইকন এবং টেক্সট ব্যবহার করে হাইলাইট করুন। পণ্যটি কেন্দ্রে ফিচার করা উচিত। ব্র্যান্ড লোগো এবং একটি বিশেষ অফার অন্তর্ভুক্ত করুন: '{discount} ছাড়'।" }
    ],
    "Food & Beverage": [
        { id: 1, en: "Generate a mouth-watering close-up photo of {product_name} on a rustic wooden table with steam and shallow depth of field. Add a small price badge: {price}.", bn: "দাগানো কাঠের টেবিলে {product_name} এর একটি চটকদার ক্লোজ-আপ ছবি তৈরি করুন, ধোঁয়া ও শ্যালো ডেপথ-অফ-ফিল্ড সহ। ছোট একটি মূল্য ব্যাজ যোগ করুন: {price}।" },
        { id: 2, en: "Dynamic action shot of {product_name} being poured or served. Use splash photography techniques. Bright, vibrant lighting. Include text '{brand_name}' in a playful font.", bn: "{product_name} ঢালা বা পরিবেশন করার একটি ডাইনামিক অ্যাকশন শট। স্প্ল্যাশ ফটোগ্রাফি কৌশল ব্যবহার করুন। উজ্জ্বল, প্রাণবন্ত আলো। '{brand_name}' লেখাটি একটি ক্রীড়নশীল ফন্টে অন্তর্ভুক্ত করুন।" },
        { id: 3, en: "A top-down shot of a table setting featuring {product_name} as the centerpiece. Cozy, restaurant ambiance. Include a '{discount} Discount' banner.", bn: "{product_name}-কে কেন্দ্র করে একটি টেবিল সেটিংয়ের টপ-ডাউন শট। আরামদায়ক, রেস্তোরাঁর পরিবেশ। একটি '{discount} ছাড়' ব্যানার অন্তর্ভুক্ত করুন।" },
        { id: 4, en: "Design a vibrant and informative social media ad for {product_name}. Show the product being enjoyed by an AI-generated person in a happy, bright setting. Incorporate the brand logo seamlessly. Include a catchy tagline and the price: {price}.", bn: "{product_name}-এর জন্য একটি প্রাণবন্ত এবং তথ্যপূর্ণ সামাজিক মিডিয়া বিজ্ঞাপন ডিজাইন করুন। একজন AI-জেনারেটেড ব্যক্তিকে একটি সুখী, উজ্জ্বল পরিবেশে পণ্যটি উপভোগ করতে দেখান। ব্র্যান্ড লোগোটি নির্বিঘ্নে অন্তর্ভুক্ত করুন। একটি আকর্ষণীয় ট্যাগলাইন এবং মূল্য অন্তর্ভুক্ত করুন: {price}।" },
        { id: 5, en: "Create an engaging infographic ad for {product_name}. Visually represent its main ingredients or nutritional facts (e.g., 'Low Calorie', 'All Natural'). Use a vibrant and fresh color scheme. Include the product image, the brand logo, and the price '{price}' in a clear layout.", bn: "{product_name}-এর জন্য একটি আকর্ষণীয় ইনফোগ্রাফিক বিজ্ঞাপন তৈরি করুন। এর প্রধান উপাদান বা পুষ্টি সম্পর্কিত তথ্য (যেমন, 'লো ক্যালোরি', 'সম্পূর্ণ প্রাকৃতিক') দৃশ্যমানভাবে উপস্থাপন করুন। একটি প্রাণবন্ত এবং তাজা রঙের স্কিম ব্যবহার করুন। পণ্যের ছবি, ব্র্যান্ড লোগো এবং মূল্য '{price}' একটি পরিষ্কার লেআউটে অন্তর্ভুক্ত করুন।" }
    ],
    "Electronics & Gadgets": [
        { id: 1, en: "Create a sleek product shot of {product_name} with a reflective surface and soft studio lights on a dark gradient background. Include text: '{brand_name} — {product_name}'.", bn: "{product_name} এর একটি আধুনিক প্রোডাক্ট শট তৈরি করুন, প্রতিফলিত পৃষ্ঠ এবং নরম স্টুডিও লাইট সহ একটি ডার্ক গ্রেডিয়েন্ট ব্যাকগ্রাউন্ডে। পাঠ্য যোগ করুন: '{brand_name} — {product_name}'।" },
        { id: 2, en: "An 'in-use' shot of {product_name} being held or used by a person in a modern home office. Focus on the product's main feature. Cinematic lighting.", bn: "একটি আধুনিক হোম অফিসে একজন ব্যক্তির দ্বারা ব্যবহৃত {product_name} এর একটি 'ইন-ইউজ' শট। পণ্যের প্রধান বৈশিষ্ট্যের উপর ফোকাস করুন। সিনেম্যাটিক আলো।" },
        { id: 3, en: "Deconstructed or exploded view of {product_name} showcasing its internal components on a clean, technical grid background. Minimalist and futuristic.", bn: "একটি পরিষ্কার, প্রযুক্তিগত গ্রিড ব্যাকগ্রাউন্ডে {product_name} এর অভ্যন্তরীণ উপাদানগুলি প্রদর্শনকারী একটি ডিকনস্ট্রাকটেড বা এক্সপ্লোডেড ভিউ। মিনিমালিস্টিক এবং ভবিষ্যৎমুখী।" },
        { id: 4, en: "Generate a futuristic ad for {product_name}. Feature an AI-generated tech enthusiast interacting with the device to highlight its key features. Place the brand logo on the product or in a corner. The ad should look informative and sleek, with text '{discount} Sale'.", bn: "{product_name}-এর জন্য একটি ভবিষ্যৎমুখী বিজ্ঞাপন তৈরি করুন। একজন AI-জেনারেটেড প্রযুক্তি উত্সাহীকে ডিভাইসের সাথে ইন্টারঅ্যাক্ট করতে দেখান যাতে এর মূল বৈশিষ্ট্যগুলি হাইলাইট হয়। ব্র্যান্ড লোগোটি পণ্যে বা এক কোণে রাখুন। বিজ্ঞাপনটি তথ্যপূর্ণ এবং মসৃণ দেখতে হবে, সাথে '{discount} Sale' লেখা থাকবে।" },
        { id: 5, en: "Generate a tech-focused infographic ad for {product_name}. Showcase its top 3 specifications (e.g., '24hr Battery', '5G Speed', '4K Display') with sleek icons and brief labels. The design should be modern and sharp. Place the brand logo prominently and show the discounted price with '{discount}'.", bn: "{product_name}-এর জন্য একটি প্রযুক্তি-কেন্দ্রিক ইনফোগ্রাফিক বিজ্ঞাপন তৈরি করুন। এর শীর্ষ ৩টি স্পেসিফিকেশন (যেমন, '২৪ ঘন্টা ব্যাটারি', '৫জি স্পিড', '৪কে ডিসপ্লে') আকর্ষণীয় আইকন এবং সংক্ষিপ্ত লেবেল দিয়ে প্রদর্শন করুন। ডিজাইনটি আধুনিক এবং শার্প হওয়া উচিত। ব্র্যান্ড লোগোটি স্পষ্টভাবে রাখুন এবং '{discount}' সহ ছাড়ের মূল্য দেখান।" }
    ],
    "Cosmetics & Beauty": [
        { id: 1, en: "Design a luxury-style photo of {product_name} on a glossy black surface with golden highlights and soft smoke. Add elegant tagline and small logo.", bn: "লাক্সারি স্টাইলের ছবি তৈরি করুন {product_name} এর, চকচকে কালো পৃষ্ঠ ও সোনালি হাইলাইট এবং নরম ধোঁয়ার সাথে। মার্জিত ট্যাগলাইন এবং ছোট লোগো যোগ করুন।" },
        { id: 2, en: "A product texture smear of {product_name} on a clean background, showing its consistency and color. Macro photography style. Add the product container next to the smear.", bn: "একটি পরিষ্কার ব্যাকগ্রাউন্ডে {product_name} এর পণ্যের টেক্সচার স্মিয়ার, যা এর ঘনত্ব এবং রঙ দেখায়। ম্যাক্রো ফটোগ্রাফি স্টাইল। স্মিয়ারের পাশে পণ্যের পাত্রটি যোগ করুন।" },
        { id: 3, en: "Natural setting photo with {product_name} placed on a stone near a gentle stream or surrounded by fresh flowers, emphasizing organic ingredients.", bn: "প্রাকৃতিক পরিবেশে {product_name}-এর ছবি, যা একটি মৃদু স্রোতের কাছে পাথরের উপর বা তাজা ফুলে ঘেরা, জৈব উপাদানগুলির উপর জোর দেয়।" },
        { id: 4, en: "Produce an elegant and informative ad for {product_name}. An AI-generated model with flawless skin should be applying or presenting the product. Use soft lighting and a clean background. Integrate the brand logo gracefully. Add a call-to-action like 'Discover Your Glow'.", bn: "{product_name}-এর জন্য একটি মার্জিত এবং তথ্যপূর্ণ বিজ্ঞাপন তৈরি করুন। নিখুঁত ত্বকের একজন AI-জেনারেটেড মডেল পণ্যটি প্রয়োগ বা উপস্থাপন করবেন। নরম আলো এবং একটি পরিষ্কার ব্যাকগ্রাউন্ড ব্যবহার করুন। ব্র্যান্ড লোগোটি সুন্দরভাবে সংহত করুন। 'Discover Your Glow'-এর মতো একটি কল-টু-অ্যাকশন যোগ করুন।" },
        { id: 5, en: "Design an informative infographic for {product_name}. Illustrate its key benefits (e.g., 'Reduces Wrinkles', 'Hydrates Skin') with elegant icons. The product texture or a swatch could be shown. Use a clean, minimalist layout with the brand logo. Add a call-to-action: 'Shop now for {price}'.", bn: "{product_name}-এর জন্য একটি তথ্যপূর্ণ ইনফোগ্রাফিক ডিজাইন করুন। এর মূল সুবিধাগুলি (যেমন, 'বলিরেখা কমায়', 'ত্বককে হাইড্রেট করে') মার্জিত আইকন দিয়ে চিত্রিত করুন। পণ্যের টেক্সচার বা একটি সোয়াচ দেখানো যেতে পারে। ব্র্যান্ড লোগো সহ একটি পরিষ্কার, মিনিমালিস্ট লেআউট ব্যবহার করুন। একটি কল-টু-অ্যাকশন যোগ করুন: 'এখনই কিনুন {price}-এ'।" }
    ],
    "Home & Decor": [
        { id: 1, en: "Produce a cozy interior mockup featuring {product_name} in a modern living room with natural light. Add brand logo watermark and price overlay {price}.", bn: "আধুনিক লিভিং রুমে প্রাকৃতিক আলোসহ {product_name} প্রদর্শিত একটি আরামদায়ক ইন্টেরিয়র মকআপ তৈরি করুন। লোগো ও মূল্য ওভারলে যোগ করুন {price}।" },
        { id: 2, en: "A close-up, detailed shot of {product_name} highlighting its material and craftsmanship. Use a contrasting background to make the texture pop.", bn: "{product_name}-এর একটি ক্লোজ-আপ, বিশদ শট যা এর উপাদান এবং কারুকার্যকে তুলে ধরে। টেক্সচারটি ফুটিয়ে তোলার জন্য একটি বিপরীত ব্যাকগ্রাউন্ড ব্যবহার করুন।" },
        { id: 3, en: "Generate an informative ad showing the {product_name} in a beautifully decorated room, with an AI-generated person admiring it. The style should be warm and inviting. Place the brand logo discreetly. Include text that highlights a key feature and the price {price}.", bn: "{product_name}-কে একটি সুন্দরভাবে সজ্জিত ঘরে প্রদর্শন করে একটি তথ্যপূর্ণ বিজ্ঞাপন তৈরি করুন, যেখানে একজন AI-জেনারেটেড ব্যক্তি এটির প্রশংসা করছেন। স্টাইলটি উষ্ণ এবং আকর্ষণীয় হওয়া উচিত। ব্র্যান্ড লোগোটি বিচক্ষণতার সাথে রাখুন। একটি মূল বৈশিষ্ট্য এবং মূল্য {price} হাইলাইট করে পাঠ্য অন্তর্ভুক্ত করুন।" },
        { id: 4, en: "Create an infographic ad for the {product_name}, highlighting its dimensions, material (e.g., 'Solid Oak Wood'), and available color options. Use a simple, clean layout that feels like a page from a design catalog. Include the brand logo and price '{price}'.", bn: "{product_name}-এর জন্য একটি ইনফোগ্রাফিক বিজ্ঞাপন তৈরি করুন, যা এর মাত্রা, উপাদান (যেমন, 'সলিড ওক উড'), এবং উপলব্ধ রঙের বিকল্পগুলি তুলে ধরে। একটি সহজ, পরিষ্কার লেআউট ব্যবহার করুন যা একটি ডিজাইন ক্যাটালগের পৃষ্ঠার মতো মনে হয়। ব্র্যান্ড লোগো এবং মূল্য '{price}' অন্তর্ভুক্ত করুন।" }
    ],
    "Fitness & Wellness": [
        { id: 1, en: "Action shot of a person using {product_name} during a workout in a modern, brightly-lit gym. Dynamic and motivational feel. Add text '{discount} Offer!'", bn: "একটি আধুনিক, উজ্জ্বলভাবে আলোকিত জিমে ওয়ার্কআউটের সময় একজন ব্যক্তির {product_name} ব্যবহার করার অ্যাকশন শট। গতিশীল এবং অনুপ্রেরণামূলক অনুভূতি। '{discount} অফার!' পাঠ্য যোগ করুন।" },
        { id: 2, en: "{product_name} placed neatly beside a yoga mat and a water bottle, with soft morning light coming from a window. Calm and serene atmosphere.", bn: "{product_name} একটি যোগা ম্যাট এবং একটি জলের বোতলের পাশে সুন্দরভাবে রাখা, জানালা দিয়ে নরম সকালের আলো আসছে। শান্ত এবং নির্মল পরিবেশ।" },
        { id: 3, en: "Create a dynamic and motivational ad with an AI-generated athlete using the {product_name}. The setting is a high-energy, modern gym. The brand logo should be visible on the product or apparel. Include an inspiring slogan and the special offer: {discount}.", bn: "একজন AI-জেনারেটেড ক্রীড়াবিদকে {product_name} ব্যবহার করে একটি গতিশীল এবং অনুপ্রেরণামূলক বিজ্ঞাপন তৈরি করুন। সেটিংটি একটি উচ্চ-শক্তির, আধুনিক জিম। ব্র্যান্ড লোগোটি পণ্য বা পোশাকে দৃশ্যমান হওয়া উচিত। একটি অনুপ্রেরণামূলক স্লোগান এবং বিশেষ অফার অন্তর্ভুক্ত করুন: {discount}।" },
        { id: 4, en: "Generate an infographic ad for {product_name}. Visually explain its benefits, such as 'Builds Muscle' or 'Boosts Energy', using dynamic icons and stats. The style should be energetic and motivational. Feature the product clearly alongside the brand logo and '{discount}' offer.", bn: "{product_name}-এর জন্য একটি ইনফোগ্রাফিক বিজ্ঞাপন তৈরি করুন। এর সুবিধাগুলি, যেমন 'পেশী তৈরি করে' বা 'শক্তি বাড়ায়', ডাইনামিক আইকন এবং পরিসংখ্যান ব্যবহার করে দৃশ্যত ব্যাখ্যা করুন। স্টাইলটি উদ্যমী এবং প্রেরণাদায়ক হওয়া উচিত। ব্র্যান্ড লোগো এবং '{discount}' অফার সহ পণ্যটি স্পষ্টভাবে ফিচার করুন।" }
    ]
};

export const RATIOS: Ratio[] = [
    { id: '1:1', label: '1:1' },
    { id: '9:16', label: '9:16' },
    { id: '16:9', label: '16:9' },
    { id: '4:5', label: '4:5' },
    { id: '3:2', label: '3:2' }
];

export const CATEGORIES = Object.keys(PROMPTS);